"""extend-user-profile-v2

Revision ID: d982f9cb51b3
Revises: 2b53fa1087c9
Create Date: 2025-11-28 19:52:30.556584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd982f9cb51b3'
down_revision: Union[str, Sequence[str], None] = '2b53fa1087c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('UserProfile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('UserProfile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
